# Generated by Django 5.2.5 on 2025-09-02 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('work_field', models.CharField(blank=True, choices=[(5, 'software engineer'), (6, 'tech guy'), (4, 'backend developer')], null=True)),
                ('profile_picture', models.ImageField(upload_to='developer_profile/')),
                ('developer_resume', models.FileField(blank=True, null=True, upload_to='developer_resume/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('github_link', models.CharField(max_length=256)),
                ('lnkedin_link', models.CharField(max_length=256)),
                ('instagram_link', models.CharField(max_length=256)),
                ('twitter_link', models.CharField(max_length=256)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('degree', models.CharField(blank=True, choices=[(3, 'PhD'), (1, 'Bachelor'), (2, 'Master')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=128)),
                ('company', models.CharField(blank=True, max_length=256, null=True)),
                ('academy', models.CharField(blank=True, max_length=256, null=True)),
                ('project_link', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(choices=[(1, 'work'), (3, 'open-source projects'), (2, 'education')])),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(default='present')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.developer')),
            ],
        ),
    ]
