# Generated by Django 5.2.5 on 2025-09-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('tech guy', 'tech guy'), ('backend developer', 'backend developer'), ('software engineer', 'software engineer')], null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('work', 'work'), ('education', 'education'), ('open-source projects', 'open-source projects')]),
        ),
    ]
