# Generated by Django 5.2.5 on 2025-09-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_alter_developer_degree_alter_developer_work_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('PhD', 'PhD'), ('Bachelor', 'Bachelor'), ('Master', 'Master')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('software engineer', 'software engineer'), ('tech guy', 'tech guy'), ('backend developer', 'backend developer')], null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('open-source projects', 'open-source projects'), ('education', 'education'), ('work', 'work')]),
        ),
    ]
