# Generated by Django 5.2.5 on 2025-09-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_developer_age_alter_developer_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('PhD', 'PhD'), ('Master', 'Master')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('backend developer', 'backend developer'), ('software engineer', 'software engineer'), ('tech guy', 'tech guy')], null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('education', 'education'), ('open-source projects', 'open-source projects'), ('work', 'work')]),
        ),
    ]
