# Generated by Django 5.2.5 on 2025-09-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_resume_description_alter_developer_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='available_to_work',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('software engineer', 'software engineer'), ('tech guy', 'tech guy'), ('backend developer', 'backend developer')], null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('open-source projects', 'open-source projects'), ('work', 'work'), ('education', 'education')]),
        ),
    ]
