# Generated by Django 5.2.5 on 2025-09-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_developer_available_to_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='academy_city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='academy_country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='academy_email',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='academy_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='academy_state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='company_city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='company_country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='company_email',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='company_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='company_state',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('PhD', 'PhD'), ('Master', 'Master'), ('Bachelor', 'Bachelor')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('software engineer', 'software engineer'), ('backend developer', 'backend developer'), ('tech guy', 'tech guy')], null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('work', 'work'), ('open-source projects', 'open-source projects'), ('education', 'education')]),
        ),
    ]
