# Generated by Django 5.2.5 on 2025-09-03 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0006_resume_academy_city_resume_academy_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('tech guy', 'tech guy'), ('software engineer', 'software engineer'), ('backend developer', 'backend developer')], null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('education', 'education'), ('open-source projects', 'open-source projects'), ('work', 'work')]),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'cli projects'), (2, 'system projects'), (3, 'web back-end'), (4, 'web front-end')], default=3)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=512)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer')),
            ],
        ),
        migrations.AddField(
            model_name='developer',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='developer.technology'),
        ),
    ]
