# Generated by Django 5.2.5 on 2025-09-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0007_technology_alter_developer_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('Master', 'Master'), ('PhD', 'PhD'), ('Bachelor', 'Bachelor')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('software engineer', 'software engineer'), ('tech guy', 'tech guy'), ('backend developer', 'backend developer')], null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.IntegerField(choices=[(2, 'system projects'), (1, 'cli projects'), (4, 'web front-end'), (3, 'web back-end')], default=3),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('open-source projects', 'open-source projects'), ('education', 'education'), ('work', 'work')]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='title',
            field=models.IntegerField(blank=True, choices=[(13, 'Qt'), (9, 'Linux'), (10, 'Bash Scripting'), (11, 'Socket Programming'), (14, 'API Development'), (6, 'AngularJS'), (5, 'VueJS'), (1, 'JavaScript'), (4, 'Postgresql'), (0, 'Python'), (15, 'GraphQL'), (2, 'Django'), (8, 'Redis'), (7, 'C - CPP'), (3, 'Rust')], null=True),
        ),
    ]
