# Generated by Django 5.2.5 on 2025-09-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0008_technology_description_alter_developer_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('PhD', 'PhD'), ('Bachelor', 'Bachelor'), ('Master', 'Master')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('tech guy', 'tech guy'), ('software engineer', 'software engineer'), ('backend developer', 'backend developer')], null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.IntegerField(choices=[(4, 'web front-end'), (3, 'web back-end'), (1, 'cli projects'), (2, 'system projects')], default=3),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('education', 'education'), ('work', 'work'), ('open-source projects', 'open-source projects')]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='title',
            field=models.CharField(blank=True, choices=[('VueJS', 'VueJS'), ('Rust', 'Rust'), ('Postgresql', 'Postgresql'), ('Bash Scripting', 'Bash Scripting'), ('Qt', 'Qt'), ('GraphQL', 'GraphQL'), ('Socket Programming', 'Socket Programming'), ('C - CPP', 'C - CPP'), ('JavaScript', 'JavaScript'), ('Python', 'Python'), ('Redis', 'Redis'), ('API Development', 'API Development'), ('Linux', 'Linux'), ('AngularJS', 'AngularJS'), ('Django', 'Django')], null=True),
        ),
    ]
