# Generated by Django 5.2.5 on 2025-09-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0009_alter_developer_degree_alter_developer_work_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('PhD', 'PhD'), ('Master', 'Master'), ('Bachelor', 'Bachelor')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('tech guy', 'tech guy'), ('software engineer', 'software engineer'), ('backend developer', 'Backend Developer')], null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.IntegerField(choices=[(2, 'system projects'), (4, 'web front-end'), (3, 'web back-end'), (1, 'cli projects')], default=3),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('work', 'work'), ('education', 'education'), ('open-source projects', 'open-source projects')]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='title',
            field=models.CharField(blank=True, choices=[('Bash Scripting', 'Bash Scripting'), ('Socket Programming', 'Socket Programming'), ('JavaScript', 'JavaScript'), ('C - CPP', 'C - CPP'), ('API Development', 'API Development'), ('Qt', 'Qt'), ('Redis', 'Redis'), ('Rust', 'Rust'), ('Postgresql', 'Postgresql'), ('GraphQL', 'GraphQL'), ('AngularJS', 'AngularJS'), ('Django', 'Django'), ('VueJS', 'VueJS'), ('Linux', 'Linux'), ('Python', 'Python')], null=True),
        ),
    ]
