# Generated by Django 5.2.5 on 2025-09-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0010_alter_developer_degree_alter_developer_work_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('Master', 'Master'), ('PhD', 'PhD'), ('Bachelor', 'Bachelor')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('backend developer', 'Backend Developer'), ('tech guy', 'tech guy'), ('software engineer', 'software engineer')], null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.IntegerField(choices=[(4, 'web front-end'), (2, 'system projects'), (3, 'web back-end'), (1, 'cli projects')], default=3),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('open-source projects', 'open-source projects'), ('work', 'work'), ('education', 'education')]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='title',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('GraphQL', 'GraphQL'), ('C - CPP', 'C - CPP'), ('Socket Programming', 'Socket Programming'), ('AngularJS', 'AngularJS'), ('Postgresql', 'Postgresql'), ('JavaScript', 'JavaScript'), ('API Development', 'API Development'), ('Bash Scripting', 'Bash Scripting'), ('Qt', 'Qt'), ('Redis', 'Redis'), ('Linux', 'Linux'), ('VueJS', 'VueJS'), ('Rust', 'Rust'), ('Django', 'Django')], null=True),
        ),
    ]
