# Generated by Django 5.2.5 on 2025-09-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0011_alter_developer_degree_alter_developer_work_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('PhD', 'PhD'), ('Bachelor', 'Bachelor'), ('Master', 'Master')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('software engineer', 'software engineer'), ('backend developer', 'Backend Developer'), ('tech guy', 'tech guy')], null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.IntegerField(choices=[(4, 'web front-end'), (1, 'cli projects'), (2, 'system projects'), (3, 'web back-end')], default=3),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('work', 'work'), ('open-source projects', 'open-source projects'), ('education', 'education')]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='title',
            field=models.CharField(blank=True, choices=[('Rust', 'Rust'), ('Python', 'Python'), ('Linux', 'Linux'), ('GraphQL', 'GraphQL'), ('Qt', 'Qt'), ('API Development', 'API Development'), ('C - CPP', 'C - CPP'), ('VueJS', 'VueJS'), ('Socket Programming', 'Socket Programming'), ('Redis', 'Redis'), ('Bash Scripting', 'Bash Scripting'), ('Postgresql', 'Postgresql'), ('JavaScript', 'JavaScript'), ('Django', 'Django'), ('AngularJS', 'AngularJS')], null=True),
        ),
    ]
