# Generated by Django 5.2.5 on 2025-09-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0012_alter_developer_degree_alter_developer_work_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('PhD', 'PhD'), ('Master', 'Master'), ('Bachelor', 'Bachelor')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('tech guy', 'tech guy'), ('backend developer', 'Backend Developer'), ('software engineer', 'software engineer')], null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.IntegerField(choices=[(1, 'cli projects'), (3, 'web back-end'), (2, 'system projects'), (4, 'web front-end')], default=3),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('open-source projects', 'open-source projects'), ('education', 'education'), ('work', 'work')]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='title',
            field=models.CharField(blank=True, choices=[('VueJS', 'VueJS'), ('Python', 'Python'), ('Linux', 'Linux'), ('GraphQL', 'GraphQL'), ('Django', 'Django'), ('Socket Programming', 'Socket Programming'), ('Rust', 'Rust'), ('C - CPP', 'C - CPP'), ('JavaScript', 'JavaScript'), ('Qt', 'Qt'), ('API Development', 'API Development'), ('AngularJS', 'AngularJS'), ('Bash Scripting', 'Bash Scripting'), ('Redis', 'Redis'), ('Postgresql', 'Postgresql')], null=True),
        ),
    ]
