# Generated by Django 5.2.5 on 2025-09-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0013_alter_developer_degree_alter_developer_work_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('Master', 'Master'), ('Bachelor', 'Bachelor'), ('PhD', 'PhD')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('backend developer', 'Backend Developer'), ('tech guy', 'tech guy'), ('software engineer', 'software engineer')], null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.IntegerField(choices=[(1, 'cli projects'), (3, 'web back-end'), (4, 'web front-end'), (2, 'system projects')], default=3),
        ),
        migrations.AlterField(
            model_name='technology',
            name='title',
            field=models.CharField(blank=True, choices=[('VueJS', 'VueJS'), ('Rust', 'Rust'), ('C - CPP', 'C - CPP'), ('Redis', 'Redis'), ('GraphQL', 'GraphQL'), ('Bash Scripting', 'Bash Scripting'), ('JavaScript', 'JavaScript'), ('Python', 'Python'), ('Qt', 'Qt'), ('Postgresql', 'Postgresql'), ('API Development', 'API Development'), ('AngularJS', 'AngularJS'), ('Django', 'Django'), ('Linux', 'Linux'), ('Socket Programming', 'Socket Programming')], null=True),
        ),
    ]
