# Generated by Django 5.2.5 on 2025-09-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0014_alter_developer_degree_alter_developer_work_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('PhD', 'PhD'), ('Master', 'Master')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('software engineer', 'software engineer'), ('backend developer', 'Backend Developer'), ('tech guy', 'tech guy')], null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.IntegerField(choices=[(4, 'web front-end'), (2, 'system projects'), (1, 'cli projects'), (3, 'web back-end')], default=3),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('work', 'work'), ('education', 'education'), ('open-source projects', 'open-source projects')]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='title',
            field=models.CharField(blank=True, choices=[('VueJS', 'VueJS'), ('Postgresql', 'Postgresql'), ('Bash Scripting', 'Bash Scripting'), ('Linux', 'Linux'), ('API Development', 'API Development'), ('Python', 'Python'), ('GraphQL', 'GraphQL'), ('AngularJS', 'AngularJS'), ('C - CPP', 'C - CPP'), ('Rust', 'Rust'), ('Redis', 'Redis'), ('Socket Programming', 'Socket Programming'), ('Qt', 'Qt'), ('Django', 'Django'), ('JavaScript', 'JavaScript')], null=True),
        ),
    ]
