# Generated by Django 5.2.5 on 2025-09-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0015_alter_developer_degree_alter_developer_work_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('PhD', 'PhD'), ('Bachelor', 'Bachelor'), ('Master', 'Master')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='skills',
            field=models.ManyToManyField(blank=True, to='developer.technology'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('backend developer', 'Backend Developer'), ('tech guy', 'tech guy'), ('software engineer', 'software engineer')], null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.IntegerField(choices=[(1, 'cli projects'), (2, 'system projects'), (3, 'web back-end'), (4, 'web front-end')], default=3),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('education', 'education'), ('work', 'work'), ('open-source projects', 'open-source projects')]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='title',
            field=models.CharField(blank=True, choices=[('Socket Programming', 'Socket Programming'), ('Postgresql', 'Postgresql'), ('AngularJS', 'AngularJS'), ('JavaScript', 'JavaScript'), ('Bash Scripting', 'Bash Scripting'), ('Python', 'Python'), ('Redis', 'Redis'), ('Qt', 'Qt'), ('Linux', 'Linux'), ('GraphQL', 'GraphQL'), ('VueJS', 'VueJS'), ('Rust', 'Rust'), ('API Development', 'API Development'), ('C - CPP', 'C - CPP'), ('Django', 'Django')], null=True),
        ),
    ]
