# Generated by Django 5.2.5 on 2025-09-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0016_alter_developer_degree_alter_developer_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('PhD', 'PhD'), ('Master', 'Master')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('tech guy', 'tech guy'), ('backend developer', 'Backend Developer'), ('software engineer', 'software engineer')], null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.IntegerField(choices=[(1, 'cli projects'), (3, 'web back-end'), (2, 'system projects'), (4, 'web front-end')], default=3),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('education', 'education'), ('open-source projects', 'open-source projects'), ('work', 'work')]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='title',
            field=models.CharField(blank=True, choices=[('Django', 'Django'), ('Redis', 'Redis'), ('Rust', 'Rust'), ('Linux', 'Linux'), ('Qt', 'Qt'), ('GraphQL', 'GraphQL'), ('Python', 'Python'), ('Socket Programming', 'Socket Programming'), ('C - CPP', 'C - CPP'), ('Bash Scripting', 'Bash Scripting'), ('VueJS', 'VueJS'), ('Postgresql', 'Postgresql'), ('AngularJS', 'AngularJS'), ('API Development', 'API Development'), ('translate', 'translate'), ('JavaScript', 'JavaScript')], null=True),
        ),
    ]
