# Generated by Django 5.2.5 on 2025-09-07 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0017_alter_developer_degree_alter_developer_work_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('PhD', 'PhD'), ('Bachelor', 'Bachelor'), ('Master', 'Master')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('software engineer', 'software engineer'), ('backend developer', 'Backend Developer'), ('tech guy', 'tech guy')], null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.IntegerField(choices=[(2, 'system projects'), (1, 'cli projects'), (4, 'web front-end'), (3, 'web back-end')], default=3),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('work', 'work'), ('education', 'education'), ('open-source projects', 'open-source projects')]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='title',
            field=models.CharField(blank=True, choices=[('AngularJS', 'AngularJS'), ('Bash Scripting', 'Bash Scripting'), ('Python', 'Python'), ('Linux', 'Linux'), ('VueJS', 'VueJS'), ('API Development', 'API Development'), ('translate', 'translate'), ('Socket Programming', 'Socket Programming'), ('Qt', 'Qt'), ('GraphQL', 'GraphQL'), ('JavaScript', 'JavaScript'), ('Postgresql', 'Postgresql'), ('Redis', 'Redis'), ('C - CPP', 'C - CPP'), ('Django', 'Django'), ('Rust', 'Rust')], null=True),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='developer.projects')),
            ],
        ),
    ]
