# Generated by Django 5.2.5 on 2025-09-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0018_alter_developer_degree_alter_developer_work_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('Master', 'Master'), ('Bachelor', 'Bachelor'), ('PhD', 'PhD')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('software engineer', 'software engineer'), ('tech guy', 'tech guy'), ('backend developer', 'Backend Developer')], null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(choices=[('web front-end', 'web front-end'), ('system projects', 'system projects'), ('web back-end', 'web back-end'), ('cli projects', 'cli projects')]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('open-source projects', 'open-source projects'), ('work', 'work'), ('education', 'education')]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='title',
            field=models.CharField(blank=True, choices=[('Django', 'Django'), ('Redis', 'Redis'), ('Linux', 'Linux'), ('Python', 'Python'), ('Bash Scripting', 'Bash Scripting'), ('C - CPP', 'C - CPP'), ('JavaScript', 'JavaScript'), ('Postgresql', 'Postgresql'), ('VueJS', 'VueJS'), ('Socket Programming', 'Socket Programming'), ('Qt', 'Qt'), ('Rust', 'Rust'), ('GraphQL', 'GraphQL'), ('translate', 'translate'), ('AngularJS', 'AngularJS'), ('API Development', 'API Development')], null=True),
        ),
    ]
