# Generated by Django 5.2.5 on 2025-09-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0019_alter_developer_degree_alter_developer_work_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('PhD', 'PhD'), ('Bachelor', 'Bachelor'), ('Master', 'Master')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('backend developer', 'Backend Developer'), ('tech guy', 'tech guy'), ('software engineer', 'software engineer')], null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(choices=[('web back-end', 'web back-end'), ('web front-end', 'web front-end'), ('cli projects', 'cli projects'), ('system projects', 'system projects')]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='title',
            field=models.CharField(blank=True, choices=[('Bash Scripting', 'Bash Scripting'), ('Django', 'Django'), ('VueJS', 'VueJS'), ('Linux', 'Linux'), ('JavaScript', 'JavaScript'), ('API Development', 'API Development'), ('Socket Programming', 'Socket Programming'), ('translate', 'translate'), ('GraphQL', 'GraphQL'), ('Qt', 'Qt'), ('AngularJS', 'AngularJS'), ('Rust', 'Rust'), ('C - CPP', 'C - CPP'), ('Python', 'Python'), ('Redis', 'Redis'), ('Postgresql', 'Postgresql')], null=True),
        ),
    ]
