# Generated by Django 5.2.5 on 2025-09-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0020_projects_link_alter_developer_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='degree',
            field=models.CharField(blank=True, choices=[('Master', 'Master'), ('Bachelor', 'Bachelor'), ('PhD', 'PhD')], null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='work_field',
            field=models.CharField(blank=True, choices=[('software engineer', 'software engineer'), ('tech guy', 'tech guy'), ('backend developer', 'Backend Developer')], null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(choices=[('cli projects', 'cli projects'), ('system projects', 'system projects'), ('web front-end', 'web front-end'), ('web back-end', 'web back-end')]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(choices=[('education', 'education'), ('open-source projects', 'open-source projects'), ('work', 'work')]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='title',
            field=models.CharField(blank=True, choices=[('Django', 'Django'), ('Qt', 'Qt'), ('Linux', 'Linux'), ('Bash Scripting', 'Bash Scripting'), ('Redis', 'Redis'), ('VueJS', 'VueJS'), ('C - CPP', 'C - CPP'), ('Socket Programming', 'Socket Programming'), ('API Development', 'API Development'), ('AngularJS', 'AngularJS'), ('Rust', 'Rust'), ('JavaScript', 'JavaScript'), ('translate', 'translate'), ('Postgresql', 'Postgresql'), ('GraphQL', 'GraphQL'), ('Python', 'Python')], null=True),
        ),
    ]
