# Generated by Django 5.2.5 on 2025-09-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='body',
            field=models.TextField(max_length=500000),
        ),
    ]
