# Generated by Django 5.2.5 on 2025-09-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_subtitle_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=64), unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
